source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

#gem "rails"
gem 'capybara'
gem "appium_lib"
gem "cucumber"
gem "appium_console"
gem "rspec"
gem 'selenium-cucumber'
gem 'selenium-webdriver'
gem 'pry'
gem 'rake'
gem "rack-test"
gem "capybara-rack_test_with_server"

